-- Course

INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15201);
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15202);
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15203);

-- Student

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#1', 'lastName#1', 'middleName#1', 18, 1, ID
FROM COURSE WHERE NUMBER = 15201;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#2', 'lastName#2', 'middleName#2', 18, 1, ID
FROM COURSE WHERE NUMBER = 15202;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#3', 'lastName#3', 'middleName#3', 18, 1, ID
FROM COURSE WHERE NUMBER = 15202;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#4', 'lastName#4', 'middleName#4', 18, 1, ID
FROM COURSE WHERE NUMBER = 15203;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#5', 'lastName#5', 'middleName#5', 18, 1, ID
FROM COURSE WHERE NUMBER = 15203;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'firstName#6', 'lastName#6', 'middleName#6', 18, 1, ID
FROM COURSE WHERE NUMBER = 15203;

-- Lecturer

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'firstName#1', 'lastName#1', 'middleName#1', 20, 'AcademicTitle#1');

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'firstName#2', 'lastName#2', 'middleName#2', 20, 'AcademicTitle#1');

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'firstName#3', 'lastName#3', 'middleName#3', 20, 'AcademicTitle#2');

-- Discipline

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Discipline#1', 'Discipline#1', PERSON.ID, COURSE.ID
FROM PERSON, COURSE
WHERE PERSON.DTYPE = 'Lecturer' AND PERSON.LAST_NAME = 'lastName#1'
AND COURSE.NUMBER = 15201;

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Discipline#2', 'Discipline#2', PERSON.ID, COURSE.ID
FROM PERSON, COURSE
WHERE PERSON.DTYPE = 'Lecturer' AND PERSON.LAST_NAME = 'lastName#2'
AND COURSE.NUMBER = 15201;

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Discipline#3', 'Discipline#3', PERSON.ID, COURSE.ID
FROM PERSON, COURSE
WHERE PERSON.DTYPE = 'Lecturer' AND PERSON.LAST_NAME = 'lastName#3'
AND COURSE.NUMBER = 15201;