-- Course
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15201); -- Introduction to Programming
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15202); -- Data Structures and Algorithms
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15203); -- Database Systems
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15204); -- Web Development
INSERT INTO COURSE (ID, NUMBER) VALUES (RANDOM_UUID(), 15205); -- Machine Learning

-- Student
-- Students for 15201 (Intro to Programming)
INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'John', 'Smith', 'Michael', 19, 'GR-101', ID FROM COURSE WHERE NUMBER = 15201;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Emily', 'Johnson', 'Anne', 20, 'GR-101', ID FROM COURSE WHERE NUMBER = 15201;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'David', 'Williams', 'Robert', 18, 'GR-102', ID FROM COURSE WHERE NUMBER = 15201;

-- Students for 15202 (Data Structures)
INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Sarah', 'Brown', 'Elizabeth', 20, 'GR-201', ID FROM COURSE WHERE NUMBER = 15202;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Michael', 'Davis', 'Thomas', 21, 'GR-201', ID FROM COURSE WHERE NUMBER = 15202;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Jessica', 'Miller', 'Marie', 19, 'GR-202', ID FROM COURSE WHERE NUMBER = 15202;

-- Students for 15203 (Database Systems)
INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Daniel', 'Wilson', 'James', 22, 'GR-301', ID FROM COURSE WHERE NUMBER = 15203;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Jennifer', 'Moore', 'Lynn', 20, 'GR-301', ID FROM COURSE WHERE NUMBER = 15203;

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, STUDY_GROUP, COURSE_ID)
SELECT RANDOM_UUID(), 'Student', 'Christopher', 'Taylor', 'Paul', 21, 'GR-302', ID FROM COURSE WHERE NUMBER = 15203;

-- Lecturer
INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'Robert', 'Anderson', 'George', 45, 'Associate Professor');

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'Elizabeth', 'Martin', 'Anne', 50, 'Professor');

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'Richard', 'Thompson', 'Edward', 38, 'PhD');

INSERT INTO PERSON (ID, DTYPE, FIRST_NAME, LAST_NAME, MIDDLE_NAME, AGE, ACADEMIC_TITLE)
VALUES (RANDOM_UUID(), 'Lecturer', 'Susan', 'Clark', 'Margaret', 42, 'Associate Professor');

-- Discipline
-- Disciplines for 15201
INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Programming Fundamentals', 'Basic syntax and programming structures', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Anderson' AND C.NUMBER = 15201;

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Object-Oriented Programming', 'Principles of OOP and design patterns', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Martin' AND C.NUMBER = 15201;

-- Disciplines for 15202
INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Data Structures', 'Implementation and analysis of common data structures', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Thompson' AND C.NUMBER = 15202;

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Algorithm Design', 'Techniques for designing efficient algorithms', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Clark' AND C.NUMBER = 15202;

-- Disciplines for 15203
INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'Relational Databases', 'Design and implementation of relational databases', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Martin' AND C.NUMBER = 15203;

INSERT INTO DISCIPLINE (ID, NAME, DESCRIPTION, LECTURER_ID, COURSE_ID)
SELECT RANDOM_UUID(), 'NoSQL Databases', 'Overview of non-relational database systems', P.ID, C.ID
FROM PERSON P, COURSE C
WHERE P.DTYPE = 'Lecturer' AND P.LAST_NAME = 'Anderson' AND C.NUMBER = 15203;